config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  resources :tasks

  # # Index
  # get 'tasks/', to: "tasks#index"

  # # New = New + Create
  # # New
  # get 'tasks/new', to: "tasks#new"
  # # Create
  # post 'tasks/', to: "tasks#create"

  # # Show
  # get 'tasks/:id', to: "tasks#show"

  # # Edit = Edit + Update
  # # Edit
  # get 'tasks/:id/edit', to: "tasks#edit"
  # # Update
  # patch 'tasks/:id', to: "tasks#update", as: "update_task"

  # # Destroy
  # delete 'tasks/:id', to: "tasks#destroy", as: "destroy_task"

  # # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
    # @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to tasks_path(task)
  end

  def edit
    # @task = Task.find(params[:id])
  end

  def update
    # @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path(@task)
  end

  def destroy
    # @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path(@task)
  end

  private

  def task_params
    task_params = params.require(:task).permit(:name, :details, :checked)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :details %>
  <%= form.text_field :details %>
  <%= form.label :checked %>
  <%= form.check_box :checked %>
  <%= form.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

<!-- <form action="<%= update_task_path(@task) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" value="<%= @task.name%>">
  <input type="text" name="description" value="<%= @task.details%>">
  <label for="checkbox">Done ?</label>
  <input type="checkbox" name="checkbox" value="Done ?">
  <button>Update</button>
</form> -->

app/views/tasks/index.html.erb
<h1>Here are all your tasks:</h1>
<ul>
  <% @tasks.each do |task|%>
  <li>
      <%= task.name %>, <%= task.details%>
  </li>
  <%= link_to 'Destroy', task_path(task), method: "delete" %>
  <% end %>
</ul>

<%= link_to 'New Task', new_task_path%>

app/views/tasks/new.html.erb
<%= render 'form' %>


<!-- <form action="<%= tasks_path %>" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="name" placeholder="Task name">
  <input type="text" name="description" placeholder="Task description">
  <label for="checkbox">Done ?</label>
  <input type="checkbox" name="checkbox" placeholder="Done ?">
  <button>Create</button>
</form> -->

app/views/tasks/show.html.erb
<h1>Selectd task: <%= @task.name %></h1>
<h2>Details: <%= @task.details %></h2>
<h2>Done? <%= @task.checked %></h2>